---

- hosts: webserver
  user: ansadm
  become: yes
  become_method: sudo

  tasks:

    - name: Install apache rpm
      yum: name=httpd state=present

    - name: Start httpd
      service: name=httpd state=started enabled=yes

    - name: Copy the standard index.html file
      copy: src=/tmp/index.html dest=/var/www/html/index.html mode=0664

    - name: Add apache iptables rule
      command: /sbin/iptables -I INPUT 1 -p tcp --dport http -j ACCEPT -m comment --comment "Apache on port 80"

    - name: Save Iptable rule
      command: iptables-save