---

## Demo playbook on ntp client config using Ansible
## Playbook use yum, service & template modules


- hosts: all
  become_user: root

  vars:
   ntp_server1: <server 1>
   ntp_server2: <server 2>

  tasks:

    # this task is to ensure chrony is not installed. Having both chrony and ntp may cause issues
    - name: remove chrony client package from the server
      yum:
       name=chrony
       state=absent
      tags: remove_chrony,start_ntp

    # this task is to ensure ntp package is installed on the server
    - name: check/install ntp client package
      yum:
       name=ntp
       state=present
      tags: install_ntp,start_ntp

    # this task is to copy ntp.conf from source server to client/target server
    - name: deploy ntp.conf file to clients
      template:
       src=templates/ntp.j2
       dest=/etc/ntp.conf
       owner=root
       group=root
       mode=0644
       backup=yes
       notify: start_restart_ntp_client
      tags: copy_ntp_conf,start_ntp

  handlers:
    # this task is to ensure that ntp service is started
    - name: start_restart_ntp_client
      service:
       name=ntpd
       state=restarted
       enabled=yes