## Using Python
# python -c 'import crypt,getpass; print crypt.crypt(getpass.getpass())'
# Above command with add random salt and prompt user to type password. This method used sha-512 as hash method.

## Using openssl: (With Random salt)
# openssl passwd -1 -salt $(openssl rand -base64 6) SecurePass

## To check the password hashing algo of the server OS
# authconfig --test | grep "password hashing algorithm"

---
- hosts: all
  user: ansadm
  become: yes
  become_method: sudo
  vars:
    user_pass:
    root_pass:

  tasks:
  - name: create new user
    user:
      name: ansible
      uid: 1113
      comment: Ansible User
      password: "{{ user_pass }}"
      shell: /bin/bash
    tags: create_user

  - name: root password change
    user: name=root update_password=always password="{{ root_pass }}"
    tags: update_root_pass