---

## Playbook on user-management using Ansible
#
- hosts: all
  become_user: root

  tasks:

    # this task creates the groups
    - name: add a group
      group:
       name={{ item }}
       state=present
      with_items:
       - Grp1
       - Grp2
       - Grp3
      tags: add_new_group

    # this task add users on target machines
    - name: add several users
      user:
       name={{ item }}
       state=present
       groups=Grp1
       password="FixStream"
       shell=/bin/bash
      with_items:
       - user1
       - user2
       - user3
       - user4
      tags: add_new_user

    # this task generates public keys for user
    - name: generate ssh keys for the user
      user:
       name={{ item }}
       generate_ssh_key=yes
       ssh_key_bits=4096
       ssh_key_file=.ssh/id_rsa
      with_items:
       - user1
      tags: generate_ssh_keys

    # this task is to copy the public keys to user account
    - name: update authorized keys for a user
      authorized_key:
       user:
        name={{ item }}
        state=present
        key= "{{ lookup('file','/home/ansadm/.ssh/id_rsa.pub') }}"
       with_items:
        - user2
        - user3
      tags: copy_pub_key

    # this task is to delete the users
    - name: delete several users
      user:
       name={{ item }}
       state=absent
      with_items:
       - user2
       - user4
      tags: remove_users

    # this task is to delete the groups
    - name: delete several groups
      group:
       name={{ item }}
       state=absent
      with_items:
       - Grp2
       - Grp3
      tags: remove_group