---

- hosts: all
  tasks:

- name: apply common configuration
  hosts: all
  user: ansadm
  become: yes
  become_method: sudo
  tasks:

  roles:
    - common

- name: install and configure apache webservers
  hosts: webservers
  user: ansadm
  become: yes
  become_method: sudo
  tasks:

  roles:
    - web
