---

- name: Install Apache Packages
  yum: name={{ item }} state=present
  with_items:
   - httpd
   - httpd-tools

- name: Copy Apache Index file
  copy: src=index.html dest=/var/www/html/index.html
  tags: apache
  notify: restart apache service
